### ISSUE TITLE
Add retry policy in sql query execution to resist network inconsistency

### ISSUE THREAD

**Issue by mfvanek** [mfvanek/pg-index-health#75]
[2020-04-09 08:04:44,663] ERROR Task execution error: class java.lang.RuntimeException
java.lang.RuntimeException: org.postgresql.util.PSQLException: Connection to <XXX>:6432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
        at io.github.mfvanek.pg.utils.QueryExecutor.executeQuery(QueryExecutor.java:110)
        at io.github.mfvanek.pg.utils.QueryExecutor.executeQueryWithSchema(QueryExecutor.java:64)
        at io.github.mfvanek.pg.index.maintenance.IndexMaintenanceImpl.executeQuery(IndexMaintenanceImpl.java:210)
        at io.github.mfvanek.pg.index.maintenance.IndexMaintenanceImpl.getPotentiallyUnusedIndexes(IndexMaintenanceImpl.java:88)
        at io.github.mfvanek.pg.index.health.IndexesHealthImpl.lambda$getUnusedIndexes$0(IndexesHealthImpl.java:102)
        at io.github.mfvanek.pg.index.health.IndexesHealthImpl.doOnHost(IndexesHealthImpl.java:188)
        at io.github.mfvanek.pg.index.health.IndexesHealthImpl.getUnusedIndexes(IndexesHealthImpl.java:101)
        at io.github.mfvanek.pg.index.health.logger.AbstractIndexesHealthLogger.logUnusedIndexes(AbstractIndexesHealthLogger.java:123)
        at io.github.mfvanek.pg.index.health.logger.AbstractIndexesHealthLogger.logAll(AbstractIndexesHealthLogger.java:64)
        at ru.yandex.market.notifier.jobs.db.maintenance.NotifierIndexesHealthLoggerJob.doJob(NotifierIndexesHealthLoggerJob.java:34)
        at ru.yandex.market.notifier.jobs.zk.AbstractJob.run(AbstractJob.java:25)
        at ru.yandex.market.checkout.common.tasks.ZooTask.fireRunnable(ZooTask.java:366)
        at ru.yandex.market.checkout.common.tasks.ZooTask.fire(ZooTask.java:357)
        at ru.yandex.market.checkout.common.tasks.ZooTask.tryToFireOnSchedule(ZooTask.java:347)
        at ru.yandex.market.checkout.common.tasks.ZooTask.runOnSchedule(ZooTask.java:292)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.postgresql.util.PSQLException: Connection to <XXX>:6432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
        at org.postgresql.Driver$ConnectThread.getResult(Driver.java:409)
        at org.postgresql.Driver.connect(Driver.java:267)
        at org.apache.commons.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:55)
        at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:355)
        at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:899)
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:429)
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:354)
        at org.apache.commons.dbcp2.PoolingDataSource.getConnection(PoolingDataSource.java:134)
        at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:753)
        at io.github.mfvanek.pg.utils.QueryExecutor.executeQuery(QueryExecutor.java:97)
        ... 15 common frames omitted
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
        at java.base/java.net.Socket.connect(Socket.java:591)
        at org.postgresql.core.PGStream.<init>(PGStream.java:75)
        at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:91)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
        at org.postgresql.Driver.makeConnection(Driver.java:458)
        at org.postgresql.Driver.access$100(Driver.java:57)
        at org.postgresql.Driver$ConnectThread.run(Driver.java:368)
        ... 1 common frames omitted

**Comment by kondratyev-nv** [comment]
@mfvanek Do you think this feature should be included in the library? In my opinion, it looks like an application has to take into account how stable its environment is, and what is the best way to implement fault-tolerant behavior around the library call.

**Comment by mfvanek** [comment]
> @mfvanek Do you think this feature should be included in the library? In my opinion, it looks like an application has to take into account how stable its environment is, and what is the best way to implement fault-tolerant behavior around the library call.

May be you are right. I'm not sure but I guess retries might be implemented within the library because the library manages connections to a database itself.

**Comment by mfvanek** [comment]
I've decided to postpone this issue for a while.
